language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "IYSG9xbIsOXPbFcAlroNYkFnGuF2G5dOyXke1SEEfqC/5yBZ8PS0ZLGQx0laH4ytliPqQAxCKMXyDIxcUhA/gBUf0kB1xESsLCHr6fjicM9YJgDL9X8OdLLKFJ3AaZHvdEzQm9V7ePzvJlJROSifddXsOFzySlbqMsxNNuZ7mF9rUR0Mw88VQK2+4aLj+5sh5bRyvPhoqU6OfwedEUk6ihntXdx6fVzurk7PALj/DKzK9l1uDbKA3ktcdaiLCzKS/roAxuTzcP1E6qzSnVN2bfVwnrXvq8J0ZH/g4taBKLsrTqfvE1g32ACaElkABV3FoHDJL3Fvn6DCwzE/PA+v3uV95Yn/qSP/HhdxZd1m9FC7oMXLLz35RKEK1fXq27jyFzNDu1qZCA/tobabPX9N73EWpGUKJjomO9AF2wpppuWXtrVugUC056Pz4CdvBnSDPkToQ/DJpX5RrMZS8vxBC3ijMLrtu6LrWibWGRZP4UG3fkm/zUAgWSR+JPVeKqdj5iRQbRPrQKxYDvFqFVWFjm2gZLngmQmEB2kW4BDf0ysB2a9KjXz6LIneriVlBRGr/wlm+zBRYMqp99cqj+wUhJKND/ZRbrbkTfW0OttLUEfWrL1HG8WUvF2IuC9E3INUT8Hfg8nsV0bhgp1uJDzfbYJnfVIPyqb5YMgTaDM1SJI="
  api_key: # 5fc4
    secure: "wOZaMsHwg/r2/eG1Hs/oin+IJWJnyXg+nSx5TKv4QQD67VBP/MLKvkEWtYFKThJAZTW/cREHXa8vse8U+SFAIv8pLYPRsUMgg89/BWcF3I1FhbvPjtcRKdjnVGTjHk4Sl6g63rkN8QMiNpne1CQwcGA/kzTeqjj0n4I/VSzS5byOmMWvZF36LdRBNfKezKWmQNTTRI43zS8lPQYBzK6BOA5jEzm5fz39XAcH7bb6XluJ6Ohiq9jAT/eLKpfBfKt6VwboGx7RP+J2v/ST0fgXkZ/lAwNkWB2w8y6RLW5hgv6zkPhkifbvVbEkZfToe+ZA+t5ueFJiLCcixP1ECoNyWfv4e+Js7D3SYnXa2WNcYD+Aajla8/RNRZ6LRYZFQr+dJj1G6BrHWBZyM0DUz4vpwIbk/x+tjEf47FHLzcB09ytVrZez6RBFqJYYBzITQZDvKnOKmrXtUl6rNuAkgplG3dzwhe70WqECuWdQO8WKQ04lvwhGGPSrxi/FE8bWYZRexwcq6awdQMxu1xR4apCZotKU4sa/wycOTVOFW8Zmuhly85yxeOL5TsjyY/XiC1Ri9TXcUSx72zthOz+XngPWEnZzl2FikMoEV8zHLRBJu7WqFaOZ4Vldh2wYsGmkmVJ3aoQGLLf3kUWuwGxpUtimOwlm7wMeXzhk0lA1+qOOcl8="
  on:
    tags: true
    node: lts/*
